#!/bin/bash

#
yum -y groupinstall "Development Libraries" "Development Tools"

# 基礎套件
yum install zlib zlib-devel gcc gcc-c++ curl curl-devel expat expat-devel gettext gett ext-devel libssh2 libssh2-devel openssh openssh-server openssl-devel memcached libyaml libyaml-devel ImageMagick ImageMagick-devel apr-devel uuid java-1.6.0-openjdk readline readline-devel glibc-devel sphinx git git-svn pcre pcre-devel sendmail perl-Net-SSLeay perl-IO-Socket-SSL  

# 服務套件
yum install httpd httpd-devel mysql mysql-server mysql-devel

# Ruby 套件
yum install ruby ruby-devel ruby-irb ruby-rdoc

#
cd /opt
#wget https://tn123.org/mod_xsendfile/mod_xsendfile.c && apxs -cia mod_xsendfile.c
yum install mod_xsendfile
wget http://www.imagemagick.org/download/linux/CentOS/i386/ImageMagick-6.6.8-4.i386.rpm && rpm -ihv --force --nodeps ImageMagick-6.6.8-4.i386.rpm

# 更新 Ruby
cd /opt
wget ftp://ftp.ruby-lang.org//pub/ruby/ruby-1.9-stable.tar.gz
tar zxvf ruby*.tar.gz && cd ruby-1.9*
./configure --enable-shared --enable-pthread && make && make install

source /etc/profile
source $HOME/.bash_profile
ldconfig

cd ext/zlib
ruby extconf.rb --with-zlib-include=/usr/include --with-zlib-lib=/usr/lib
cd ../../
make && make install

source /etc/profile
source $HOME/.bash_profile
ldconfig

# 更新 RubyGems
cd /opt
wget http://production.cf.rubygems.org/rubygems/rubygems-1.6.2.tgz
tar zxvf rubygems*.tgz && cd rubygems* && ruby setup.rb

source /etc/profile
source $HOME/.bash_profile
ldconfig
updatedb

# 安裝 Gems

#gem install abstract  actionmailer  actionpack  activemodel  activerecord  activeresource  activesupport  allison  arel  builder  builder  bundler cgi_multipart_eof_fix  chronic  daemon_controller  daemons  diff-lcs  echoe  erubis  eventmachine fastthread  file-tail  gemcutter  gem_plugin  geoip  hoe  i18n  json  json_pure  mail mime-types mongrel  passenger  polyglot  rack rack-mount rack-test  rails  railties  rake  rdiscount  rmagick rubyforge  ruby-hmac  ruby-openid  ruby-yadis  spruz  stomp  stompserver  thin  thor treetop  tzinfo

#gem install rack --version=1.0.1

echo <<EOF
please install these gems (** be ware of the version! **):

abstract-1.0.0.gem
actionmailer-2.3.6.gem
actionpack-2.3.6.gem
actionpack-3.0.1.gem
activemodel-3.0.1.gem
activerecord-2.3.6.gem
activerecord-3.0.1.gem
activeresource-2.3.6.gem
activesupport-2.3.6.gem
activesupport-3.0.1.gem
allison-2.0.3.gem
arel-1.0.1.gem
builder-2.1.2.gem
bundler-1.0.3.gem
cgi_multipart_eof_fix-2.5.0.gem
chronic-0.3.0.gem
daemon_controller-0.2.5.gem
daemons-1.1.0.gem
diff-lcs-1.1.2.gem
echoe-4.3.1.gem
erubis-2.6.6.gem
eventmachine-0.12.10.gem
fastthread-1.0.7.gem
file-tail-1.0.5.gem
gemcutter-0.6.1.gem
gem_plugin-0.2.3.gem
geoip-0.8.7.gem
hoe-2.6.2.gem
i18n-0.5.0.gem
json-1.4.6.gem
json_pure-1.4.6.gem
mail-2.2.9.gem
mime-types-1.16.gem
mongrel-1.1.5.gem
passenger-3.0.0.gem
polyglot-0.3.1.gem
rack-1.0.1.gem
rack-mount-0.6.13.gem
rack-test-0.5.6.gem
rails-2.3.6.gem
railties-3.0.1.gem
rake-0.8.7.gem
rdiscount-1.3.1.1.gem
rmagick-2.13.1.gem
rubyforge-2.0.4.gem
ruby-hmac-0.4.0.gem
ruby-openid-2.1.8.gem
ruby-yadis-0.3.4.gem
spruz-0.2.1.gem
stomp-1.1.gem
stompserver-0.9.9.gem
thin-1.2.7.gem
thor-0.14.4.gem
treetop-1.4.8.gem
tzinfo-0.3.23.gem
EOF
