#!/bin/bash

adduser --create-home git

echo "export RUBY_HOME=/usr/local" >> /home/git/.bashrc
echo "export GEM_HOME=\$RUBY_HOME/lib/ruby/gems/1.8/gems" >> /home/git/.bashrc
echo "export PATH=\$RUBY_HOME/bin:\$PATH" >> /home/git/.bashrc
source /home/git/.bashrc

mkdir -p /home/git/.ssh
chmod 700 /home/git/.ssh
touch /home/git/.ssh/authorized_keys
chmod 600 /home/git/.ssh/authorized_keys
chown -R git.git /home/git

cd /var/www/html
git clone git://gitorious.org/gitorious/mainline.git gitorious
chown -R git.git gitorious

chmod ug+x gitorious/script/*

mkdir -p git/repositories git/tarballs-work git/tarballs-cache

cd -
cp gitorious.conf /etc/httpd/conf.d/gitorious.conf
cp gitorious-poller /etc/init.d/
cp git-ultrasphinx /etc/init.d/
cp git-daemon /etc/init.d/
cp stomp /etc/init.d/

cp broker.yml /var/www/html/gitorious/conf/
cp database.yml /var/www/html/gitorious/conf/
cp gitorious.yml /var/www/html/gitorious/conf/

chown -R git.git /var/www/html/gitorious

chkconfig --add stomp
chkconfig --add git-daemon
chkconfig --add gitorious-poller
chkconfig --add git-ultrasphinx
chkconfig --add memcached

chkconfig stomp on
chkconfig git-daemon on
chkconfig gitorious-poller on
chkconfig git-ultrasphinx on
chkconfig memcached on

service git-ultrasphinx start
service stomp start
service memcached start
service gitorious-poller start
service git-daemon start
service httpd restart

echo "127.0.0.1 gitorious" >> /etc/hosts

cd /var/www/html/gitorious
rake gems:install
rake db:create RAILS_ENV=production
rake db:migrate RAILS_ENV=production
rake ultrasphinx:configure RAILS_ENV=production
rake ultrasphinx:index RAILS_ENV=production
rake ultrasphinx:daemon:start RAILS_ENV=production 

echo "* * * * * cd /var/www/html/gitorious && rake ultrasphinx:index RAILS_ENV=production" > /var/spool/cron/git
chown git.root /var/spool/cron/git
chmod 600 /var/spool/cron/git

updatedb
