#!/bin/bash

cp gitorious.conf /etc/httpd/conf.d/gitorious.conf
cp gitorious-poller /etc/init.d/
cp git-ultrasphinx /etc/init.d/
cp git-daemon /etc/init.d/
cp stomp /etc/init.d/

cp broker.yml /var/www/html/gitorious/conf/
cp database.yml /var/www/html/gitorious/conf/
cp gitorious.yml /var/www/html/gitorious/conf/

chown -R git.git /var/www/html/gitorious

chkconfig --add stomp
chkconfig --add git-daemon
chkconfig --add gitorious-poller
chkconfig --add git-ultrasphinx
chkconfig --add memcached

chkconfig stomp on
chkconfig git-daemon on
chkconfig gitorious-poller on
chkconfig git-ultrasphinx on
chkconfig memcached on

service git-ultrasphinx start
service stomp start
service memcached start
service gitorious-poller start
service git-daemon start
service httpd restart

updatedb
